version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/golang:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build
          command: docker build -t ${OWNER}/${IMAGE_NAME}:latest .
      - run:
          name: Save image
          command: docker image save ${OWNER}/${IMAGE_NAME}:latest > ./docker-image.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./docker-image.tar
  test:
    docker:
      - image: circleci/golang:latest
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load image from tar
          command: docker load -i ./docker-image.tar
      - run:
          name: Test
          command: docker run ${OWNER}/${IMAGE_NAME}:latest td help:all
  push:
    docker:
      - image: circleci/golang:latest
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load image from tar
          command: docker load -i ./docker-image.tar
      - run:
          name: Tag to latest
          command: docker tag ${OWNER}/${IMAGE_NAME}:latest ${OWNER}/${IMAGE_NAME}:${CIRCLE_TAG}
      - run:
          name: Docker Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Push image to registory
          command: docker push ${OWNER}/${IMAGE_NAME}
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - push:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
